pipeline {
  agent any
  environment {
    DOCKER_IMAGE = "juannguyen0211/huan-gametetris-mp:latest"
	  CLUSTER_NAME = "huan-tetris-cluster"
    REGION       = "ap-southeast-1"
  }
  
  stages {
    stage('Checkout') {
      steps {
        deleteDir() // Clean workspace before checkout
        checkout scm
      }
    }
  
    stage('Build Docker Image') {
      steps {
        sh 'docker build -t $DOCKER_IMAGE .'
      }
    }
    stage('Push Docker Image') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
          sh 'echo $PASSWORD | docker login -u $USERNAME --password-stdin'
          sh 'docker push $DOCKER_IMAGE'
        }
      }
    }
    stage('Deploy to EKS') {
      steps {
        dir('terraform/manifests') {
          withAWS(credentials: 'aws-access-creds', region: "${REGION}") {
            sh 'aws eks --region="$REGION" update-kubeconfig --name="$CLUSTER_NAME"'
            sh 'kubectl apply -f 01.namespace.yaml'
            sh 'kubectl apply -f 02.deployment.yaml'
            sh 'kubectl apply -f 03.service.yaml'
            sh 'kubectl apply -f 04.ingress.yaml'
          }
        } 
      }
    }
  }
}
